version: '3.8'

services:
  backend:
    image: tronfit-server
    build: .
    container_name: tronfit-be
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: npm run start

  postgres:
    image: postgres:17-alpine
    container_name: tronfit-postgres-db
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - type: volume
        source: tronfit_postgres_dev_data
        target: /var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5432:5432"

volumes:
  tronfit_postgres_dev_data:
    driver: local

# networks: nếu muốn tách riêng network
# healthcheck: để check container healthy

# Chạy tất cả services (background): docker-compose up -d
# Chỉ build lại và chạy docker-compose up --build

