name: 📋 Task
description: General task, improvement, or maintenance
title: "[TASK] "
labels: ["type:task", "status:ready"]
assignees: []

body:
  - type: input
    id: task-title
    attributes:
      label: Task Title
      description: Clear description of what needs to be done
      placeholder: "Implement JWT authentication middleware"
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - "🔌 API - REST/GraphQL endpoints, middleware"
        - "🗄️ Database - Schema changes, migrations, queries"
        - "🔐 Auth - Authentication, authorization, security"
        - "🐛 Fix - Non-critical bug fixes and improvements"
        - "🔧 Maintenance - Code cleanup, refactoring"
        - "⚡ Performance - Database optimization, caching"
        - "🧪 Testing - Unit tests, integration tests"
        - "📚 Documentation - API docs, README, comments"
        - "📦 Dependencies - Update libraries, packages"
        - "🔒 Security - Security audits, vulnerability fixes"
        - "🏗️ Infrastructure - Docker, deployment, CI/CD"
        - "📊 Monitoring - Logging, metrics, health checks"
        - "🌐 Integration - Third-party services, webhooks"
        - "📧 Messaging - Email, SMS, push notifications"
        - "📁 File Management - Upload/download, storage"
        - "⚙️ Configuration - Environment variables, settings"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - "🔥 Critical - Security issue or system down"
        - "⚡ High - Blocking other work or user-facing"
        - "📊 Medium - Normal priority"
        - "📝 Low - Nice to have, when time permits"
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the task
      placeholder: |
        Current authentication system uses basic auth which is not secure enough.
        Need to implement JWT-based authentication with refresh tokens.
        
        Requirements:
        - Support login/logout endpoints
        - JWT tokens with 15min expiry
        - Refresh tokens with 7 days expiry
        - Middleware to protect routes
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Task Breakdown
      description: List of specific tasks to complete
      placeholder: |
        - [ ] Design JWT token structure
        - [ ] Create auth middleware
        - [ ] Implement login endpoint
        - [ ] Implement logout endpoint
        - [ ] Add token refresh endpoint
        - [ ] Update protected routes
        - [ ] Write unit tests
        - [ ] Update API documentation
        - [ ] Test integration
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work is this?
      options:
        - "⏱️ Small - Less than 4 hours"
        - "📅 Medium - 1-2 days"
        - "📆 Large - 3-5 days"
        - "🗓️ Extra Large - 1+ weeks"
      default: 0
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Technical considerations, architecture decisions, or dependencies
      placeholder: |
        - Database changes required: Yes/No
        - Breaking changes: Yes/No
        - External services affected: None
        - Performance impact: Minimal
        - Security considerations: High - involves authentication

  - type: checkboxes
    id: backend-checklist
    attributes:
      label: Backend Checklist
      description: Please confirm
      options:
        - label: I have clearly defined the task and requirements
          required: true
        - label: I have broken down the work into steps
          required: true
        - label: I have considered database schema changes
          required: false
        - label: I have identified potential breaking changes
          required: false
        - label: I have considered security implications
          required: false